<?php

return [
    'dropdowns' => [
        'nationalities' => [
            1 => 'US',
            2 => 'India',
            2 => 'UK',
            3 => 'Australia',
            4 => 'New Zealand',
        ],
        'current_levels' => [
            1 => 'Recreational',
            2 => 'School',
            3 => 'Sunday League',
            4 => 'District',
            5 => 'County',
            6 => 'Saturday League',
            7 => 'National League Academy',
            8 => 'EFL Academy',
            9 => 'Premier League Academy',
            10 => 'National League Senior',
            11 => 'EFL Senior',
        ],
        'highest_levels' => [
            1 => 'Recreational',
            2 => 'School',
            3 => 'Sunday League',
            4 => 'District',
            5 => 'County',
            6 => 'Saturday League',
            7 => 'National League Academy',
            8 => 'EFL Academy',
            9 => 'Premier League Academy',
            10 => 'National League Senior',
            11 => 'EFL Senior',
        ],
        'positions' => [
            1 => 'Goalkeeper (GK)',
            2 => 'Centre Back (CB)',
            3 => 'Right Back (RB)',
            4 => 'Left Back (LB)',
            5 => 'Centre Midfield (CM)',
            6 => 'Centre Defensive Midfield (CDM)',
            7 => 'Centre Attacking Midfield (CAM)',
            8 => 'Right Midfield (RM)',
            9 => 'Left Midfield (LM)',
            10 => 'Right Wing (RW)',
            11 => 'Left Wing (LW)',
            12 => 'Centre Forward (CF)',
        ],
        'second_positions' => [
            1 => 'Goalkeeper (GK)',
            2 => 'Centre Back (CB)',
            3 => 'Right Back (RB)',
            4 => 'Left Back (LB)',
            5 => 'Centre Midfield (CM)',
            6 => 'Centre Defensive Midfield (CDM)',
            7 => 'Centre Attacking Midfield (CAM)',
            8 => 'Right Midfield (RM)',
            9 => 'Left Midfield (LM)',
            10 => 'Right Wing (RW)',
            11 => 'Left Wing (LW)',
            12 => 'Centre Forward (CF)',
        ],
        'feet' => [
            1 => 'Right',
            2 => 'Left',
            3 => 'Both',
        ],
        'traits' => [
            1 => 'Agile',
            2 => 'Aggressive',
            3 => 'Distance',
            4 => 'Distribution',
            5 => 'Dribbler',
            6 => 'Finisher',
            7 => 'Handling',
            8 => 'Judgement',
            9 => 'Leadership',
            10 => 'Long',
            11 => 'Play',
            12 => 'Power',
            13 => 'Set',
            14 => 'Speedster',
            15 => 'Strength',
            16 => 'Tackler',
            17 => 'Tactician',
            18 => 'Team',
            19 => 'Vocal',
        ]
    ]
];